contract events {
  event Approval               (address indexed owner, address indexed spender, uint value);
  event BalanceUpdate          (address indexed owner, uint newAmount);
  event DSAuthorityUpdate      (address indexed newAuthority);
  event DSOwnerUpdate          (address indexed newOwner);
  event DSSetCanCall           (address caller, address callee, bytes4 sig, bool newCanCall);
  event LogAuctionReversal     (uint indexed auctionID);
  event LogBid                 (uint indexed auctionletID);
  event LogNewAuction          (uint indexed newID, uint baseID);
  event LogSplit               (uint baseID, uint newID, uint splitID);
  event SetNullable            (bytes32 indexed key, bytes32 indexed value, bool indexed isSet);
  event Transfer               (address indexed from, address indexed to, uint value);
  event Updated                (uint indexed id);
  event _log_gas_use           (uint gas);
  event eventListener          (address target, bool exact);
  event log_address            (address value);
  event log_bool               (bool value);
  event log_bytes              (bytes value);
  event log_bytes1             (bytes1 value);
  event log_bytes10            (bytes10 value);
  event log_bytes11            (bytes11 value);
  event log_bytes12            (bytes12 value);
  event log_bytes13            (bytes13 value);
  event log_bytes14            (bytes14 value);
  event log_bytes15            (bytes15 value);
  event log_bytes16            (bytes16 value);
  event log_bytes17            (bytes17 value);
  event log_bytes18            (bytes18 value);
  event log_bytes19            (bytes19 value);
  event log_bytes2             (bytes2 value);
  event log_bytes20            (bytes20 value);
  event log_bytes21            (bytes21 value);
  event log_bytes22            (bytes22 value);
  event log_bytes23            (bytes23 value);
  event log_bytes24            (bytes24 value);
  event log_bytes25            (bytes25 value);
  event log_bytes26            (bytes26 value);
  event log_bytes27            (bytes27 value);
  event log_bytes28            (bytes28 value);
  event log_bytes29            (bytes29 value);
  event log_bytes3             (bytes3 value);
  event log_bytes30            (bytes30 value);
  event log_bytes31            (bytes31 value);
  event log_bytes32            (bytes32 value);
  event log_bytes4             (bytes4 value);
  event log_bytes5             (bytes5 value);
  event log_bytes6             (bytes6 value);
  event log_bytes7             (bytes7 value);
  event log_bytes8             (bytes8 value);
  event log_bytes9             (bytes9 value);
  event log_int                (int value);
  event log_named_address      (bytes32 name, address value);
  event log_named_bool         (bytes32 name, bool value);
  event log_named_bytes        (bytes32 name, bytes value);
  event log_named_bytes1       (bytes32 name, bytes1 value);
  event log_named_bytes10      (bytes32 name, bytes10 value);
  event log_named_bytes11      (bytes32 name, bytes11 value);
  event log_named_bytes12      (bytes32 name, bytes12 value);
  event log_named_bytes13      (bytes32 name, bytes13 value);
  event log_named_bytes14      (bytes32 name, bytes14 value);
  event log_named_bytes15      (bytes32 name, bytes15 value);
  event log_named_bytes16      (bytes32 name, bytes16 value);
  event log_named_bytes17      (bytes32 name, bytes17 value);
  event log_named_bytes18      (bytes32 name, bytes18 value);
  event log_named_bytes19      (bytes32 name, bytes19 value);
  event log_named_bytes2       (bytes32 name, bytes2 value);
  event log_named_bytes20      (bytes32 name, bytes20 value);
  event log_named_bytes21      (bytes32 name, bytes21 value);
  event log_named_bytes22      (bytes32 name, bytes22 value);
  event log_named_bytes23      (bytes32 name, bytes23 value);
  event log_named_bytes24      (bytes32 name, bytes24 value);
  event log_named_bytes25      (bytes32 name, bytes25 value);
  event log_named_bytes26      (bytes32 name, bytes26 value);
  event log_named_bytes27      (bytes32 name, bytes27 value);
  event log_named_bytes28      (bytes32 name, bytes28 value);
  event log_named_bytes29      (bytes32 name, bytes29 value);
  event log_named_bytes3       (bytes32 name, bytes3 value);
  event log_named_bytes30      (bytes32 name, bytes30 value);
  event log_named_bytes31      (bytes32 name, bytes31 value);
  event log_named_bytes32      (bytes32 name, bytes32 value);
  event log_named_bytes4       (bytes32 name, bytes4 value);
  event log_named_bytes5       (bytes32 name, bytes5 value);
  event log_named_bytes6       (bytes32 name, bytes6 value);
  event log_named_bytes7       (bytes32 name, bytes7 value);
  event log_named_bytes8       (bytes32 name, bytes8 value);
  event log_named_bytes9       (bytes32 name, bytes9 value);
  event log_named_decimal_int  (bytes32 name, int value, uint decimals);
  event log_named_decimal_uint (bytes32 name, uint value, uint decimals);
  event log_named_int          (bytes32 name, int value);
  event log_named_string       (string name, string value);
  event log_named_uint         (bytes32 name, uint value);
  event log_uint               (uint value);
  event logs                   (bytes value);
}
